image_size: 128
learning:
  batch_size: 32
  epochs: 10
  dropout: 0.3
  learning_rate: 0.001
  shuffle: True 
  drop_last: True
  device: "cuda"
  milestones: [50, 75]
  gamma: 0.1
  save_experiment: True
