data:
  path: data/data_labo
  image_size: 256
  num_classes: 19
  background_classes: 4
  transforms:
    run_rotation: false
    run_hflip: true
    run_vflip: true
    color:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.0
      hue: 0.0

model:
  name: resnet    # choose between resnet, adversarial, unet
  resnet:
    hidden_size: 64
    p_dropout: 0.1
  adversarial:
    hidden_size: 256
    p_dropout: 0.1

learning:
  epochs: 10
  batch_size: 8
  learning_rate_resnet: 0.00001 #0,0001 original
  learning_rate_adversary: 0.001
  shuffle: true 
  drop_last: true
  device: cuda
  save_experiment: true
  save_checkpoint: true
  loss: crossentropy
  num_workers: 2
  alpha: 10
