image_size: 128
name: "resnet18"
learning:
  batch_size: 32
  epochs: 3
  dropout: 0.3
  learning_rate_resnet: 0.0001
  learning_rate_adversary: 0.001
  shuffle: True 
  drop_last: True
  device: "cuda"
  milestones: [50, 75]
  gamma: 0.1
  save_experiment: "true"
  save_checkpoint: "true"
  loss: "CrossEntropyLoss"
