name: "resnet18"

data:
  path: data_transform
  image_size: 128
  num_classes: 2
  background_classes: 4
  transforms:
    run_rotation: false
    run_hflip: true
    run_vflip: true
    color:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.0
      hue: 0.0

model:
  name: resnet    # choose between resnet and adversarial
  resnet:
    hidden_size: 64
    p_dropout: 0.1
  adversarial:
    hidden_size: 256
    p_dropout: 0.1


learning:
  batch_size: 32
  epochs: 10
  dropout: 0.3
  learning_rate_resnet: 0.0001
  learning_rate_adversary: 0.001
  shuffle: true 
  drop_last: true
  device: cuda
  milestones: [50, 75]
  gamma: 0.1
  save_experiment: true
  save_checkpoint: true
  loss: crossentropy
  num_workers: 2
